Require Import UniMath.Algebra.Lattice.
Require Import UniMath.Combinatorics.StandardFiniteSets.
Require Import UniMath.Combinatorics.FiniteSets.
Require Import UniMath.Foundations.Sets.
Require Import UniMath.Foundations.Propositions.
Require Import UniMath.MoreFoundations.Propositions.
Require Import UniMath.MoreFoundations.Subtypes.

(* A free bounded distributive lattice is a distributive lattice with 0 and 1 that is freely generated by a set. *)
(* Distributivity of two binary operations defined in UniMath.Algebra.BinaryOperations. as isrdistr/isldistr/isdistr *)
(* Subsets defined in MoreFoundations/Sets *)

(** Free bounded distributive lattice on a finite set of generators.
We define it as finite irredundant sets of finite subsets of the generators.
Join is union and then removing redundant sets.
Meet is pairwise union and then removing redundant sets.
See https://en.wikipedia.org/wiki/Distributive_lattice#Free_distributive_lattices. *)

(* 0 is the empty join. *)
(* 1 is the empty meet. *)

Open Scope stn.
Open Scope subtype.
Open Scope logic.


Section fbdl.

Declare Scope fbdl.

(* The powerset *)
Notation "'ℙ' X" := (hsubtype X) (at level 10).

(* Finite subsets of finite subsets of X (meet and joins are finite) *)
Definition finsub (X : UU) : UU :=
  ∑ P : ℙ (ℙ X), isfinite P × ∏ S : P, isfinite (pr1 S).

(* We construct the elements of an fbdl as a quotient on ℙ (ℙ X) *)
Definition remove_redundant_sets {X : UU} (P : ℙ (ℙ X)) : ℙ (ℙ X) :=
  λ S, (((S ,, tt) : ∑ (_ : ℙ X), htrue) ∈ P) ∧ (∀ (T : P), (pr1 T) ⊆ S ⇒ (pr1 T) ≡ S).

(* Two elements are equivalent if they reduce to the same normal form of joins of meets. *)
Definition fbdl_el {X : UU} : hSet.
Proof.
  apply (@setquotinset (finsub X)).
  intros P Q.
  exact (remove_redundant_sets (pr1 P) ≡ remove_redundant_sets (pr1 Q)).
Defined.
